# Generated by Django 6.0.1 on 2026-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='atendido',
            field=models.BooleanField(default=False, verbose_name='¿Solicitud Atendida?'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='notas_internas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Operador (Internas)'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta Prioridad'), ('Media', 'Prioridad Normal'), ('Baja', 'Baja Prioridad')], default='Media', max_length=20, verbose_name='Nivel de Prioridad'),
        ),
    ]
