# Generated by Django 6.0.1 on 2026-04-16 08:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_contacto_atendido_contacto_notas_internas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='notas_internas',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notas del Operador (Internas)'),
        ),
    ]
