# Generated by Django 6.0.1 on 2026-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_reporteproblema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='alcance_proyecto',
            field=models.CharField(choices=[('Local', 'Nivel Local / Barrio'), ('Municipal', 'Nivel Municipal'), ('Estatal', 'Nivel Estatal / Nacional')], default='Local', max_length=20, verbose_name='Alcance del Proyecto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Revisión'), ('Evaluando', 'Evaluando Requisitos'), ('Contactado', 'Ciudadano Contactado'), ('Cerrado', 'Caso Cerrado')], default='Pendiente', max_length=20, verbose_name='Estado Interno'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='presupuesto_aprox',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto Estimado ($)'),
        ),
        migrations.AddField(
            model_name='reporteproblema',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido por Sistema'), ('Revisión', 'En Revisión Analítica'), ('Desplegando', 'Desplegando Equipo/Dron'), ('Resuelto', 'Incidente Resuelto')], default='Recibido', max_length=20, verbose_name='Estado Operativo'),
        ),
        migrations.AddField(
            model_name='reporteproblema',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='reportes_evidencia/', verbose_name='Evidencia Visual'),
        ),
        migrations.AddField(
            model_name='reporteproblema',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud Geográfica'),
        ),
        migrations.AddField(
            model_name='reporteproblema',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud Geográfica'),
        ),
    ]
