# Generated by Django 6.0.1 on 2026-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cotizacion_alcance_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='servicio_interes',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Servicio de Interés'),
        ),
    ]
